### ISSUE TITLE
Example update/create call

### ISSUE THREAD

**Issue by ikeforrest** [scoop/autotask_api#6]
Any chance you could post an example of an update and create call?

**Comment by scoop** [comment]
`AutotaskAPI::Client` will take an XML document to update an existing object with since Autotask doesn't support partial updates.

If you start with a result from `AutotaskAPI::Client#entities_for(query)` you can use Nokogiri to parse the raw XML result, change what you want to change, and then pass the remains back to `AutotaskAPI::Client#update` it should give you the result you want.

Abbreviated example to update the territory of an existing account:

```ruby
result = @client.entities_for(@query)
doc = Nokogiri::XML::DocumentFragment.parse(result.first.raw_xml)
new_territory = Nokogiri::XML::Node.new "TerritoryID", doc
new_territory.content = 29689230
doc.at_css('Entity').add_child new_territory
@client.update doc.to_xml
```
